-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 19:51:12 2017
-- Model: petshop    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema petshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `petshop` ;

-- -----------------------------------------------------
-- Schema petshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petshop` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci ;
USE `petshop` ;

-- -----------------------------------------------------
-- Create user
-- -----------------------------------------------------
DROP USER `sispetshop`@`localhost`;
CREATE USER `sispetshop`@`localhost` identified by "123456";
GRANT ALL PRIVILEGES ON petshop.* TO `sispetshop`@`localhost`;
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Table `petshop`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petshop`.`produtos` ;

CREATE TABLE IF NOT EXISTS `petshop`.`produtos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `preco` DECIMAL(10,2) NOT NULL COMMENT '',
  `imagem` VARCHAR(60) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petshop`.`users` ;

CREATE TABLE IF NOT EXISTS `petshop`.`users` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(191) NOT NULL COMMENT '',
  `email` VARCHAR(191) NOT NULL COMMENT '',
  `password` VARCHAR(191) NOT NULL COMMENT '',
  `type` SMALLINT(6) NOT NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petshop`.`compras` ;

CREATE TABLE IF NOT EXISTS `petshop`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `produtos_id` INT(10) NOT NULL COMMENT '',
  `users_id` INT(10) NOT NULL COMMENT '',
  `quantidade` SMALLINT(6) NOT NULL COMMENT '',
  `data` DATETIME NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`, `produtos_id`, `users_id`)  COMMENT '',
  INDEX `fk_produtos_has_users_users1_idx` (`users_id` ASC)  COMMENT '',
  INDEX `fk_produtos_has_users_produtos_idx` (`produtos_id` ASC)  COMMENT '',
  CONSTRAINT `fk_produtos_has_users_produtos`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `petshop`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `petshop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `type`) VALUES(1, 'Maria Silva', 'silva@hotmail.com', '462010',2);
INSERT INTO `users` (`id`, `name`, `email`, `password`, `type`) VALUES(2, 'José Santos', 'santos@hotmail.com', '429841',3);
INSERT INTO `users` (`id`, `name`, `email`, `password`, `type`) VALUES(3, 'Antônio Oliveira', 'oliveira@hotmail.com', '463441',3);
INSERT INTO `users` (`id`, `name`, `email`, `password`, `type`) VALUES(4, 'João Souza', 'souza@hotmail.com', '326472',3);
INSERT INTO `users` (`id`, `name`, `email`, `password`, `type`) VALUES(5, 'Francisco Pereira', 'pereira@hotmail.com', '340015',1);
INSERT INTO `users` (`id`, `name`, `email`, `password`, `type`) VALUES(6, 'Ana Costela', 'costela@hotmail.com', '420191',1);
INSERT INTO `users` (`id`, `name`, `email`, `password`, `type`) VALUES(7, 'Luiz Carvalho', 'carval@hohotmail.com', '448211',1);
INSERT INTO `users` (`id`, `name`, `email`, `password`, `type`) VALUES(8, 'Paulo Almeida', 'almeida@hotmail.com', '318871',1);
INSERT INTO `users` (`id`, `name`, `email`, `password`, `type`) VALUES(9, 'Carlos Ferreira', 'ferreira@hotmail.com', '429972',1);
INSERT INTO `users` (`id`, `name`, `email`, `password`, `type`) VALUES(10, 'Manoel Ribeiro', 'ribeiro@hotmail.com', '481967',1);

ALTER TABLE `users` AUTO_INCREMENT = 11;


--
-- Dumping data for table `produtos`
--

INSERT INTO `produtos` (`id`, `nome`, `preco`, `imagem`) VALUES(1, 'Dog Show Gourmet', 9.60, 'imagens/dogshow.jpg');
INSERT INTO `produtos` (`id`, `nome`, `preco`, `imagem`) VALUES(2, 'Shampoo Dog', 6, 'imagens/shampoo.jpg');
INSERT INTO `produtos` (`id`, `nome`, `preco`, `imagem`) VALUES(3, 'Bolinha', 3.5, 'imagens/bolinha.jpg');
INSERT INTO `produtos` (`id`, `nome`, `preco`, `imagem`) VALUES(4, 'Osso', 2, 'imagens/osso.jpg');
INSERT INTO `produtos` (`id`, `nome`, `preco`, `imagem`) VALUES(5, 'Coleira', 6, 'imagens/coleira.jpg');

ALTER TABLE `produtos` AUTO_INCREMENT = 6;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
